### ISSUE TITLE
"edit" command crashes

### ISSUE THREAD

**Issue by kkga** [doy/rbw#60]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/kkga/.cargo/registry/src/github.com-1ecc6299db9ec823/rbw-1.2.0/src/edit.rs:44:10
```

I've tried setting different values for the `EDITOR` variable, but it seems to have no effect.

**Comment by doy** [comment]
does /usr/bin/vim exist on your system? what other values for `EDITOR` did you try?

**Comment by kkga** [comment]
I've any console text editor available on my system (vim, nvim, nano, kak), but it still shows the same error.

```
~ > whereis vim
vim: /usr/bin/vim /usr/share/vim /usr/share/man/man1/vim.1

~ > rbw edit GitHub
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/kkga/.cargo/registry/src/github.com-1ecc6299db9ec823/rbw-1.3.0/src/edit.rs:44:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

~ > EDITOR=/usr/bin/nano rbw edit GitHub
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/kkga/.cargo/registry/src/github.com-1ecc6299db9ec823/rbw-1.3.0/src/edit.rs:44:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by doy** [comment]
do you have the `VISUAL` env var set?

**Comment by kkga** [comment]
> do you have the `VISUAL` env var set?

This did the trick, thanks.

**Comment by das-s** [comment]
I ran into the same error when `VISUAL` is set with editor flags, e.g.`export VISUAL="emacsclient -c"` or `export VISUAL="vim -v"`.  Editing without editor flags works though. Could this be related to insufficient escaping?
